#!/usr/bin/env bash
# PreToolUse hook: block hand-edits to NSwag-generated TypeScript clients.
#
# Claude Code invokes this script with the tool-call JSON on stdin whenever
# Edit / Write / MultiEdit runs. If the target path looks like a generated API
# client, we exit with code 2 so the tool call is rejected and Claude reads
# stderr as guidance.
#
# Protected paths:
#   - web/src/api/generated.ts
#   - mobile/src/api/generated.ts
#   - any path ending in /api/generated.ts (belt-and-braces)

set -euo pipefail

LOG_DIR="${CLAUDE_PROJECT_DIR:-.}/.claude/hooks/log"
mkdir -p "$LOG_DIR"
LOG="$LOG_DIR/$(date +%F).log"

payload="$(cat)"

# Extract file_path from tool_input. Use jq if available; otherwise fall back
# to a grep that tolerates the shapes Edit / Write / MultiEdit send.
if command -v jq >/dev/null 2>&1; then
    file_path="$(printf '%s' "$payload" | jq -r '.tool_input.file_path // empty')"
else
    file_path="$(printf '%s' "$payload" \
        | grep -oE '"file_path"[[:space:]]*:[[:space:]]*"[^"]+"' \
        | head -n1 \
        | sed -E 's/.*"file_path"[[:space:]]*:[[:space:]]*"([^"]+)".*/\1/')"
fi

if [[ -z "${file_path:-}" ]]; then
    # No file path in payload — nothing to guard. Allow the call.
    exit 0
fi

case "$file_path" in
    */web/src/api/generated.ts|*/mobile/src/api/generated.ts|*/api/generated.ts)
        printf '[%s] block-generated-edits: BLOCKED %s\n' \
          "$(date -Iseconds)" "$file_path" >> "$LOG"
        cat >&2 <<'MSG'
Blocked: src/api/generated.ts is auto-generated by NSwag and must not be
hand-edited. If the API contract changed, regenerate the client via the
`regen-api` skill instead:

  cd web && npm run generate-api

To extend behaviour, add wrappers in src/api/client.ts or a sibling module.
MSG
        exit 2
        ;;
esac

exit 0
