/* eslint-disable */
// @ts-nocheck
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import axios, { AxiosError } from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

export class ApiClient {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "https://localhost:5001";

    }

    /**
     * Update current user profile
     * @return No Content
     */
    updateProfileEndpoint(updateProfileRequest: UpdateProfileRequest, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/users/me";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(updateProfileRequest);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "PUT",
            url: url_,
            headers: {
                "Content-Type": "application/json",
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processUpdateProfileEndpoint(_response);
        });
    }

    protected processUpdateProfileEndpoint(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = JSON.parse(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status === 401) {
            const _responseText = response.data;
            return throwException("Unauthorized", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Get current user profile
     * @return Success
     */
    getProfileEndpoint(signal?: AbortSignal): Promise<GetProfileResponse> {
        let url_ = this.baseUrl + "/users/me";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetProfileEndpoint(_response);
        });
    }

    protected processGetProfileEndpoint(response: AxiosResponse): Promise<GetProfileResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<GetProfileResponse>(result200);

        } else if (status === 401) {
            const _responseText = response.data;
            return throwException("Unauthorized", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<GetProfileResponse>(null as any);
    }

    /**
     * Delete current user account
     * @return No Content
     */
    deleteAccountEndpoint(signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/users/me";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "DELETE",
            url: url_,
            headers: {
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processDeleteAccountEndpoint(_response);
        });
    }

    protected processDeleteAccountEndpoint(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status === 401) {
            const _responseText = response.data;
            return throwException("Unauthorized", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Invite a client
     * @return Success
     */
    inviteClientEndpoint(inviteClientRequest: InviteClientRequest, signal?: AbortSignal): Promise<InviteClientResponse> {
        let url_ = this.baseUrl + "/trainer/clients/invite";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(inviteClientRequest);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processInviteClientEndpoint(_response);
        });
    }

    protected processInviteClientEndpoint(response: AxiosResponse): Promise<InviteClientResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<InviteClientResponse>(result200);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = JSON.parse(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status === 401) {
            const _responseText = response.data;
            return throwException("Unauthorized", status, _responseText, _headers);

        } else if (status === 403) {
            const _responseText = response.data;
            return throwException("Forbidden", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<InviteClientResponse>(null as any);
    }

    /**
     * Get trainer's clients
     * @param page Page number (1-based). Defaults to 1.
     * @param pageSize Number of items per page. Defaults to 20.
     * @param search (optional) Optional search filter by client name or email.
     * @return Success
     */
    getClientsEndpoint(page: number, pageSize: number, search?: string | null | undefined, signal?: AbortSignal): Promise<GetClientsResponse> {
        let url_ = this.baseUrl + "/trainer/clients?";
        if (page === undefined || page === null)
            throw new globalThis.Error("The parameter 'page' must be defined and cannot be null.");
        else
            url_ += "page=" + encodeURIComponent("" + page) + "&";
        if (pageSize === undefined || pageSize === null)
            throw new globalThis.Error("The parameter 'pageSize' must be defined and cannot be null.");
        else
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        if (search !== undefined && search !== null)
            url_ += "search=" + encodeURIComponent("" + search) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetClientsEndpoint(_response);
        });
    }

    protected processGetClientsEndpoint(response: AxiosResponse): Promise<GetClientsResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<GetClientsResponse>(result200);

        } else if (status === 401) {
            const _responseText = response.data;
            return throwException("Unauthorized", status, _responseText, _headers);

        } else if (status === 403) {
            const _responseText = response.data;
            return throwException("Forbidden", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<GetClientsResponse>(null as any);
    }

    /**
     * Get client dashboard
     * @param clientId The client's public ID, provided as a route parameter.
     * @return Success
     */
    getClientDashboardEndpoint(clientId: string, signal?: AbortSignal): Promise<GetClientDashboardResponse> {
        let url_ = this.baseUrl + "/trainer/clients/{clientId}";
        if (clientId === undefined || clientId === null)
            throw new globalThis.Error("The parameter 'clientId' must be defined.");
        url_ = url_.replace("{clientId}", encodeURIComponent("" + clientId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetClientDashboardEndpoint(_response);
        });
    }

    protected processGetClientDashboardEndpoint(response: AxiosResponse): Promise<GetClientDashboardResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<GetClientDashboardResponse>(result200);

        } else if (status === 401) {
            const _responseText = response.data;
            return throwException("Unauthorized", status, _responseText, _headers);

        } else if (status === 403) {
            const _responseText = response.data;
            return throwException("Forbidden", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<GetClientDashboardResponse>(null as any);
    }

    /**
     * Create collaboration
     * @return Success
     */
    createCollaborationEndpoint(createCollaborationRequest: CreateCollaborationRequest, signal?: AbortSignal): Promise<CreateCollaborationResponse> {
        let url_ = this.baseUrl + "/trainer/collaborations";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(createCollaborationRequest);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processCreateCollaborationEndpoint(_response);
        });
    }

    protected processCreateCollaborationEndpoint(response: AxiosResponse): Promise<CreateCollaborationResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<CreateCollaborationResponse>(result200);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = JSON.parse(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status === 401) {
            const _responseText = response.data;
            return throwException("Unauthorized", status, _responseText, _headers);

        } else if (status === 403) {
            const _responseText = response.data;
            return throwException("Forbidden", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<CreateCollaborationResponse>(null as any);
    }

    /**
     * Reset password
     * @return No Content
     */
    resetPasswordEndpoint(resetPasswordRequest: ResetPasswordRequest, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/auth/password/reset";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(resetPasswordRequest);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "PUT",
            url: url_,
            headers: {
                "Content-Type": "application/json",
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processResetPasswordEndpoint(_response);
        });
    }

    protected processResetPasswordEndpoint(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = JSON.parse(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Request password reset
     * @return No Content
     */
    requestPasswordResetEndpoint(requestPasswordResetRequest: RequestPasswordResetRequest, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/auth/password/reset";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(requestPasswordResetRequest);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processRequestPasswordResetEndpoint(_response);
        });
    }

    protected processRequestPasswordResetEndpoint(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = JSON.parse(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Register a new user
     * @return Success
     */
    registerEndpoint(registerRequest: RegisterRequest, signal?: AbortSignal): Promise<RegisterResponse> {
        let url_ = this.baseUrl + "/auth/register";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(registerRequest);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processRegisterEndpoint(_response);
        });
    }

    protected processRegisterEndpoint(response: AxiosResponse): Promise<RegisterResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200 || status === 201) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<RegisterResponse>(result200);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = JSON.parse(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status !== 200 && status !== 201 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<RegisterResponse>(null as any);
    }

    /**
     * Refresh access token
     * @return Success
     */
    refreshTokenEndpoint(refreshTokenRequest: RefreshTokenRequest, signal?: AbortSignal): Promise<RefreshTokenResponse> {
        let url_ = this.baseUrl + "/auth/refresh";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(refreshTokenRequest);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processRefreshTokenEndpoint(_response);
        });
    }

    protected processRefreshTokenEndpoint(response: AxiosResponse): Promise<RefreshTokenResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<RefreshTokenResponse>(result200);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = JSON.parse(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<RefreshTokenResponse>(null as any);
    }

    /**
     * Logout user
     * @return No Content
     */
    logoutEndpoint(logoutRequest: LogoutRequest, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/auth/logout";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(logoutRequest);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processLogoutEndpoint(_response);
        });
    }

    protected processLogoutEndpoint(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status === 401) {
            const _responseText = response.data;
            return throwException("Unauthorized", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Authenticate user
     * @return Success
     */
    loginEndpoint(loginRequest: LoginRequest, signal?: AbortSignal): Promise<LoginResponse> {
        let url_ = this.baseUrl + "/auth/login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(loginRequest);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processLoginEndpoint(_response);
        });
    }

    protected processLoginEndpoint(response: AxiosResponse): Promise<LoginResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<LoginResponse>(result200);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = JSON.parse(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<LoginResponse>(null as any);
    }

    /**
     * Accept a trainer invitation
     * @return Success
     */
    acceptInvitationEndpoint(acceptInvitationRequest: AcceptInvitationRequest, signal?: AbortSignal): Promise<AcceptInvitationResponse> {
        let url_ = this.baseUrl + "/auth/invite/accept";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(acceptInvitationRequest);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processAcceptInvitationEndpoint(_response);
        });
    }

    protected processAcceptInvitationEndpoint(response: AxiosResponse): Promise<AcceptInvitationResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = JSON.parse(resultData200);
            return Promise.resolve<AcceptInvitationResponse>(result200);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = JSON.parse(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status === 401) {
            const _responseText = response.data;
            return throwException("Unauthorized", status, _responseText, _headers);

        } else if (status === 403) {
            const _responseText = response.data;
            return throwException("Forbidden", status, _responseText, _headers);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<AcceptInvitationResponse>(null as any);
    }
}

/** Request model for updating the authenticated user's profile. */
export interface UpdateProfileRequest {
    /** Updated first name. */
    firstName: string;
    /** Updated last name. */
    lastName: string;
}

/** the dto used to send an error response to the client */
export interface ErrorResponse {
    /** the http status code sent to the client. default is 400. */
    statusCode?: number;
    /** the message for the error response */
    message?: string;
    /** the collection of errors for the current context */
    errors?: { [key: string]: string[]; };
}

/** Response model for the authenticated user's profile. */
export interface GetProfileResponse {
    /** User's public ID. */
    userId?: string;
    /** User's email address. */
    email?: string;
    /** User's first name. */
    firstName?: string;
    /** User's last name. */
    lastName?: string;
    /** User's assigned roles. */
    roles?: string[];
    /** Date and time when the account was created. */
    dateCreated?: string;
}

/** Response model returned after sending a client invitation. */
export interface InviteClientResponse {
    /** Confirmation message. */
    message?: string;
    /** Invitation token (exposed for dev/testing; would be emailed in production). */
    invitationToken?: string;
}

/** Request model for inviting a client via email. */
export interface InviteClientRequest {
    /** Email address of the client to invite. */
    email: string;
}

/** Response model for the trainer's client list. */
export interface GetClientsResponse {
    /** List of client summaries. */
    clients?: ClientSummary[];
    /** Total number of clients matching the filter. */
    totalCount?: number;
    /** Current page number. */
    page?: number;
    /** Number of items per page. */
    pageSize?: number;
}

/** Summary of a client in the trainer's client list. */
export interface ClientSummary {
    /** Client profile's public ID. */
    publicId?: string;
    /** Client's email address. */
    email?: string;
    /** Client's first name. */
    firstName?: string;
    /** Client's last name. */
    lastName?: string;
    /** Whether this trainer-client relationship is active. */
    isActive?: boolean;
    /** Date when the trainer-client relationship was established. */
    linkedAt?: string;
}

/** Request model for retrieving a trainer's client list with pagination. */
export interface GetClientsRequest {
}

/** Response model containing a client's dashboard summary for a trainer. */
export interface GetClientDashboardResponse {
    /** The client profile's public ID. */
    clientPublicId?: string;
    /** The client's email address. */
    email?: string;
    /** The client's first name. */
    firstName?: string;
    /** The client's last name. */
    lastName?: string;
    /** The client's date of birth. */
    dateOfBirth?: string | undefined;
    /** The client's height in centimeters. */
    heightCm?: number | undefined;
    /** The client's current weight in kilograms. */
    weightKg?: number | undefined;
    /** The client's fitness or health goals. */
    goals?: string | undefined;
    /** Date when the trainer-client relationship was established. */
    linkedAt?: string;
    /** Whether the trainer-client relationship is currently active. */
    isActive?: boolean;
    /** Total number of body measurements recorded for the client. */
    totalMeasurements?: number;
    /** Total number of progress photos uploaded for the client. */
    totalProgressPhotos?: number;
    /** The most recent body measurement, or null if none exist. */
    latestMeasurement?: LatestMeasurementDto | undefined;
}

/** Summary of the most recent body measurement for a client. */
export interface LatestMeasurementDto {
    /** Date and time when the measurement was taken. */
    measuredAt?: string;
    /** Weight in kilograms. */
    weightKg?: number | undefined;
    /** Body fat percentage. */
    bodyFatPercentage?: number | undefined;
}

/** Request model for retrieving a client's dashboard summary. */
export interface GetClientDashboardRequest {
}

/** Response model for a successfully created collaboration. */
export interface CreateCollaborationResponse {
    /** A message describing the result of the operation. */
    message?: string;
}

/** Request model for creating a collaboration between a trainer and another professional for a shared client. */
export interface CreateCollaborationRequest {
    /** The public ID of the client to share with the collaborator. */
    clientPublicId: string;
    /** The public ID of the collaborator's ProfessionalProfile. */
    collaboratorPublicId: string;
}

/** Request model for completing a password reset using a token. */
export interface ResetPasswordRequest {
    /** The password reset token received via email. */
    token: string;
    /** The user's email address. */
    email: string;
    /** The new password. */
    newPassword: string;
    /** Confirmation of the new password. */
    confirmPassword: string;
}

/** Request model for initiating a password reset. */
export interface RequestPasswordResetRequest {
    /** Email address of the account to reset. */
    email: string;
}

/** Response model returned after successful registration. */
export interface RegisterResponse {
    /** The newly created user's public ID. */
    userId?: string;
    /** The user's email address. */
    email?: string;
    /** Confirmation message. */
    message?: string;
}

/** Request model for user registration. */
export interface RegisterRequest {
    /** User's email address (used as login). */
    email: string;
    /** User's chosen password. */
    password: string;
    /** Password confirmation (must match Password). */
    confirmPassword: string;
    /** User's first name. */
    firstName: string;
    /** User's last name. */
    lastName: string;
    /** The role the user is registering as. */
    role: string;
    /** Explicit GDPR consent for processing health data. */
    gdprConsent?: boolean;
}

/** Response model returned after successful token refresh. */
export interface RefreshTokenResponse {
    /** New JWT access token. */
    accessToken?: string;
    /** New refresh token (old one is invalidated via rotation). */
    refreshToken?: string;
    /** New access token expiration time in UTC. */
    expiresAt?: string;
}

/** Request model for refreshing an access token using a refresh token. */
export interface RefreshTokenRequest {
    /** The current refresh token to exchange for a new token pair. */
    refreshToken: string;
}

/** Request model for logging out (revoking a refresh token). */
export interface LogoutRequest {
    /** The refresh token to revoke. */
    refreshToken?: string;
}

/** Response model returned after successful login. */
export interface LoginResponse {
    /** JWT access token (short-lived, 15 minutes). */
    accessToken?: string;
    /** Refresh token for obtaining new access tokens (7 days). */
    refreshToken?: string;
    /** Access token expiration time in UTC. */
    expiresAt?: string;
}

/** Request model for user login. */
export interface LoginRequest {
    /** User's email address. */
    email: string;
    /** User's password. */
    password: string;
}

/** Response model returned after successfully accepting an invitation. */
export interface AcceptInvitationResponse {
    /** Confirmation message. */
    message?: string;
    /** Public identifier of the trainer whose invitation was accepted. */
    trainerPublicId?: string;
}

/** Request model for accepting a trainer's invitation. */
export interface AcceptInvitationRequest {
    /** The one-time invitation token received from the trainer. */
    token: string;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}

function isAxiosError(obj: any): obj is AxiosError {
    return obj && obj.isAxiosError === true;
}