using System.ComponentModel.DataAnnotations;

namespace FitnessPlatform.Application.Domain.Entities;

/// <summary>
/// A server-issued, single-use, short-lived nonce used to harden social sign-in against
/// identity-token replay attacks. The client requests a nonce via POST /auth/social/nonce,
/// embeds it in the Apple/Google sign-in flow, and presents it together with the resulting
/// identity token. The backend validates the token's embedded nonce against the stored value,
/// then marks the row consumed to prevent replay.
/// </summary>
public class SocialLoginNonce
{
    /// <summary>
    /// Primary key (auto-generated by the database).
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// The raw nonce value (base64url of 32 random bytes). Indexed with a unique constraint
    /// so lookups are O(log n) and collisions are caught by the DB.
    /// </summary>
    [MaxLength(64)]
    public string Nonce { get; set; } = string.Empty;

    /// <summary>
    /// UTC timestamp after which the nonce is considered expired and must be rejected.
    /// </summary>
    public DateTime ExpiresAt { get; set; }

    /// <summary>
    /// UTC timestamp when the nonce was consumed (i.e. successfully validated by a
    /// sign-in attempt). Null until consumed. A non-null value means the nonce is
    /// single-use-spent and must be rejected on any subsequent attempt.
    /// </summary>
    public DateTime? ConsumedAt { get; set; }

    /// <summary>
    /// UTC timestamp when this row was created (set on insert).
    /// </summary>
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}
