blank_issues_enabled: false
contact_links:
  - name: 💬 Question or discussion
    url: https://github.com/JanProkorat/fitness-platform/discussions
    about: Use Discussions for open-ended questions, ideas, or support.
