using Npgsql;
using Testcontainers.MongoDb;
using Testcontainers.PostgreSql;

// Registers SharedTestContainers as an xUnit v3 assembly fixture (native to xunit.v3 3.2.2 —
// confirmed against xunit.v3.extensibility.core's own XML docs; no separate package needed,
// unlike xUnit v2's Xunit.Extensions.AssemblyFixture add-on). xUnit initializes it once before
// any test in the assembly runs and disposes it once after every test has run — the exact
// lifecycle a single shared container pair needs. TestAssemblyConfig.cs (the
// [assembly: CollectionBehavior(...)] attribute) is left untouched by #1104 Phase B; this
// attribute lives here instead so that file's serial-execution decision stays undisturbed.
[assembly: AssemblyFixture(typeof(FitnessPlatform.Tests.Infrastructure.SharedTestContainers))]

namespace FitnessPlatform.Tests.Infrastructure;

/// <summary>
/// Boots exactly ONE Postgres and ONE Mongo Testcontainer for the whole test run (#1104 Phase
/// B), replacing the ~20 per-collection/per-factory containers Phase A left in place. Every
/// fixture that used to build its own <see cref="PostgreSqlContainer"/> /
/// <see cref="MongoDbContainer"/> now takes a <see cref="SharedTestContainers"/> constructor
/// parameter instead — xUnit resolves any assembly fixture requested this way, the same
/// composition it already uses for <see cref="ICollectionFixture{TFixture}"/> — and asks this
/// class for an isolated database inside the shared servers rather than an isolated server.
///
/// Container teardown is left to Testcontainers' own Ryuk resource reaper (it removes any
/// container/network it created once the client process that started it exits or disconnects),
/// backed up by this class's own <see cref="DisposeAsync"/> once xUnit calls it after the last
/// test finishes. No manual process-exit hook is needed on top of that.
/// </summary>
public sealed class SharedTestContainers : IAsyncLifetime
{
    private PostgreSqlContainer? _postgres;
    private MongoDbContainer? _mongo;

    /// <summary>
    /// The shared Postgres container's connection string, pointed at its own default
    /// "postgres" administrative database. Fixtures that need an isolated schema/data set call
    /// <see cref="CreatePostgresDatabaseAsync"/> instead of connecting to this directly.
    /// </summary>
    public string PostgresConnectionString => _postgres?.GetConnectionString()
        ?? throw new InvalidOperationException(
            $"{nameof(SharedTestContainers)}.{nameof(InitializeAsync)} has not completed yet.");

    /// <summary>
    /// The shared Mongo container's connection string. Mongo creates databases implicitly on
    /// first write, so — unlike Postgres — no admin call is needed before a name generated by
    /// <see cref="CreateMongoDatabaseName"/> can be used directly against this connection.
    /// </summary>
    public string MongoConnectionString => _mongo?.GetConnectionString()
        ?? throw new InvalidOperationException(
            $"{nameof(SharedTestContainers)}.{nameof(InitializeAsync)} has not completed yet.");

    /// <inheritdoc />
    public async ValueTask InitializeAsync()
    {
        _postgres = new PostgreSqlBuilder("postgres:16").Build();
        _mongo = new MongoDbBuilder("mongo:7").Build();

        await Task.WhenAll(
            _postgres.StartAsync(),
            _mongo.StartAsync());
    }

    /// <inheritdoc />
    public async ValueTask DisposeAsync()
    {
        await Task.WhenAll(
            _postgres?.DisposeAsync().AsTask() ?? Task.CompletedTask,
            _mongo?.DisposeAsync().AsTask() ?? Task.CompletedTask);
    }

    /// <summary>
    /// Creates a fresh, empty Postgres database inside the shared container and returns a
    /// connection string pointed at it. Postgres — unlike Mongo — requires the database to
    /// exist before a connection can select it, so this issues a <c>CREATE DATABASE</c>
    /// against the container's default database first.
    /// </summary>
    /// <param name="namePrefix">A short, identifiable prefix (e.g. the fixture's name) so a
    /// developer inspecting the running container mid-debug can tell fixtures apart.</param>
    public async Task<string> CreatePostgresDatabaseAsync(string namePrefix)
    {
        var databaseName = BuildUniqueDatabaseName(namePrefix);

        await using (var adminConnection = new NpgsqlConnection(PostgresConnectionString))
        {
            await adminConnection.OpenAsync();
            await using var command = adminConnection.CreateCommand();
            command.CommandText = $"CREATE DATABASE \"{databaseName}\"";
            await command.ExecuteNonQueryAsync();
        }

        var builder = new NpgsqlConnectionStringBuilder(PostgresConnectionString)
        {
            Database = databaseName,
        };
        return builder.ConnectionString;
    }

    /// <summary>
    /// Generates a fresh, unused Mongo database name inside the shared container. Mongo has no
    /// server-level "create database" step — the name only needs to be unique among fixtures;
    /// the database springs into existence on the first write against it.
    /// </summary>
    public static string CreateMongoDatabaseName(string namePrefix) => BuildUniqueDatabaseName(namePrefix);

    private static string BuildUniqueDatabaseName(string namePrefix) => $"{namePrefix}_{Guid.NewGuid():N}";
}
